Use kernelModuleMakeFlags in place of kernel.makeFlags
Refer to commit 5645cd22d4a4 ("linux: expose make flags for modules in
linuxKernel.packages.linux_X_Y").

Resolves:
  source root is NVIDIA-Linux-x86_64-590.48.01/kernel-open
  setting SOURCE_DATE_EPOCH to timestamp 1765203993 of file "NVIDIA-Linux-x86_64-590.48.01/kernel-open/nvidia/nvidia-sources.Kbuild"
  Running phase: patchPhase
  Running phase: updateAutotoolsGnuConfigScriptsPhase
  Running phase: configurePhase
  no configure script, doing nothing
  Running phase: buildPhase
  build flags: -j4 SHELL=/nix/store/i27rhb3nr65rkrwz36bchkwmav6ggsmn-bash-5.3p9/bin/bash O=\$\(buildRoot\) --eval=undefine modules CC=/nix/store/sanx9fg8mry8mq92zhlm5qvb83qlxrlx-gcc-15.2.0/bin/gcc LD=/nix/store/p2vkw5s89ff1fs2d2rxqxiqil9s0jpcm-binutils-2.46/bin/ld AR=/nix/store/qd70v8g0561vm8m33kmnp79z00cgyi5n-gcc-wrapper-15.2.0/bin/ar NM=/nix/store/qd70v8g0561vm8m33kmnp79z00cgyi5n-gcc-wrapper-15.2.0/bin/nm STRIP=/nix/store/p2vkw5s89ff1fs2d2rxqxiqil9s0jpcm-binutils-2.46/bin/strip OBJCOPY=/nix/store/qd70v8g0561vm8m33kmnp79z00cgyi5n-gcc-wrapper-15.2.0/bin/objcopy OBJDUMP=/nix/store/qd70v8g0561vm8m33kmnp79z00cgyi5n-gcc-wrapper-15.2.0/bin/objdump READELF=/nix/store/qd70v8g0561vm8m33kmnp79z00cgyi5n-gcc-wrapper-15.2.0/bin/readelf HOSTCC=/nix/store/qd70v8g0561vm8m33kmnp79z00cgyi5n-gcc-wrapper-15.2.0/bin/cc HOSTCXX=/nix/store/qd70v8g0561vm8m33kmnp79z00cgyi5n-gcc-wrapper-15.2.0/bin/c++ HOSTAR=/nix/store/kfwagnh6i1mysf7vxq679rzh30z9zj3g-binutils-wrapper-2.46/bin/ar HOSTLD=/nix/store/kfwagnh6i1mysf7vxq679rzh30z9zj3g-binut
  make: *** empty variable name.  Stop.
  error: builder for '/nix/store/1s86s7fd2r2hj8idmh0wnk7a2q519j8x-nvidia-open-6.18.26-590.48.01.drv' failed with exit code 2;

Link: https://github.com/NixOS/nixpkgs/commit/5645cd22d4a4ed66449986cd96f49ebc043cb5d6
Signed-off-by: Rahul Rameshbabu <sergeantsagara@protonmail.com>